# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/nuxt-ssr-firebase
    docker:
      - image: circleci/node:8.11.2
    steps:
      - checkout
      - run: cd src && yarn install
      - run: cd functions && yarn install
      - run: cd src && yarn build
