version: 2  

jobs:
  Building:
    working_directory: ~/nuxt-ssr-firebase
    docker:
      - image: circleci/node:8.11.2
    steps:
      - checkout
      - restore_cache:
          key: v1-node_modules-{{ checksum "/src/yarn.lock" }}
      - restore_cache:
          key: v1-node_modules-{{ checksum "/functions/yarn.lock" }}
      - run:
          name: Install deps from Nuxt project
          command: cd src && yarn install
      - run:
          name: Install deps from Firebase Functions project
          command: cd functions && yarn install
      - save_cache:
          key: v1-node_modules-{{ checksum "/src/yarn.lock" }}
      - save_cache:
          key: v1-node_modules-{{ checksum "/functions/yarn.lock" }}
      - run:
          name: Build Nuxt project
          command: cd src && yarn build
      - run:
          name: Create public folder to static files
          command: mkdir public
      - run:
          name: Copy files from nuxt folder to public folder
          command: cp -R functions/nuxt/dist/ public
  Deploy on Firebase Functions and Hosting:
    working_directory: ~/nuxt-ssr-firebase
    docker:
      - image: circleci/node:8.11.2
    steps:
      - run:
          name: Deploy on firebase
          command: cd functions && ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
workflows:
  version: 2
  Build and deploy:
    jobs:
      - Building
      - Deploy on Firebase Functions and Hosting:
          requires:
            - Building
